"""Constrained, read-only SQL execution for the "Ask the Data" chat agent.

This hands a network-facing LLM the ability to query hr_analytics.db directly,
which needs a real safety boundary, not just a well-worded system prompt. Two
independent layers:

1. validate_query() -- a fast-fail allowlist (single SELECT/WITH statement, no
   DDL/DML/PRAGMA/ATTACH, forced row limit) that rejects obviously-wrong queries
   with a message the agent can read and self-correct from.
2. run_read_only_query() -- opens the database via a SQLite URI with mode=ro.
   This OS/SQLite-level read-only file descriptor is the actual security
   boundary: even a gap in the regex allowlist above can't write to the
   database, because the connection is physically incapable of it. `PRAGMA
   query_only = ON` is defense in depth on top of that, not the primary
   guarantee. See DECISIONS.md for why this two-layer design was chosen over
   either a pure-parameterized tool set or unconstrained SQL generation.
"""

from __future__ import annotations

import re
import sqlite3
import time
from pathlib import Path

DB_PATH = Path("data/processed/hr_analytics.db")

MAX_ROWS = 50  # doubles as both the safety cap and the context-window budget for tool results
QUERY_TIMEOUT_SECONDS = 5.0

_STATEMENT_START = re.compile(r"^\s*(SELECT|WITH)\b", re.IGNORECASE)
_FORBIDDEN_KEYWORDS = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|REPLACE|ATTACH|DETACH|PRAGMA|VACUUM|REINDEX|TRIGGER)\b",
    re.IGNORECASE,
)
_LIMIT_CLAUSE = re.compile(r"\bLIMIT\s+\d+\b", re.IGNORECASE)


class UnsafeQueryError(ValueError):
    """Raised when a query fails the safety allowlist. The message is written
    to be readable by the calling LLM so it can retry with a corrected query."""


def validate_query(sql: str) -> str:
    stripped = sql.strip()
    if stripped.endswith(";"):
        stripped = stripped[:-1].strip()
    if ";" in stripped:
        raise UnsafeQueryError("Only a single statement is allowed -- remove the extra ';' and any text after it.")
    if not _STATEMENT_START.match(stripped):
        raise UnsafeQueryError("Only SELECT or WITH...SELECT statements are allowed.")
    if _FORBIDDEN_KEYWORDS.search(stripped):
        raise UnsafeQueryError("Query contains a disallowed keyword (only read-only SELECT queries are permitted).")
    # Strip any user-supplied LIMIT and unconditionally append ours -- don't
    # just cap it if larger, since a query with no LIMIT at all would
    # otherwise return every row.
    stripped = _LIMIT_CLAUSE.sub("", stripped).rstrip()
    return f"{stripped} LIMIT {MAX_ROWS}"


def _execute_on_read_only_connection(sql: str, params: tuple, db_path: Path) -> list[dict]:
    """Shared by both callers below: opens the same mode=ro connection either
    way. Not exported -- callers must go through run_read_only_query() (for
    untrusted, LLM-authored SQL text) or execute_parameterized() (for
    trusted, hardcoded SQL text with untrusted *values*), never this directly,
    so it's always clear which safety contract applies to a given call site."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA query_only = ON")
        deadline = time.monotonic() + QUERY_TIMEOUT_SECONDS
        conn.set_progress_handler(lambda: 1 if time.monotonic() > deadline else 0, 1000)
        cursor = conn.execute(sql, params)
        rows = cursor.fetchmany(MAX_ROWS)
        return [dict(row) for row in rows]
    finally:
        conn.close()


def run_read_only_query(sql: str, db_path: Path = DB_PATH) -> list[dict]:
    """For untrusted, free-form SQL text (e.g. LLM-generated) -- goes through
    validate_query()'s allowlist first."""
    validated = validate_query(sql)
    return _execute_on_read_only_connection(validated, (), db_path)


def execute_parameterized(sql: str, params: tuple = (), db_path: Path = DB_PATH) -> list[dict]:
    """For trusted, hardcoded SQL text (written by us, not generated by the
    LLM) with untrusted *values* bound in via '?' placeholders -- e.g. a
    parameterized tool like get_attrition_rate(department=...) where
    `department` comes from LLM-supplied tool arguments. Using placeholders
    here instead of string-interpolating those values into SQL is correct
    practice even though the read-only connection already prevents a write --
    an interpolated value could still corrupt the query's WHERE-clause logic
    (e.g. a value like "Sales' OR '1'='1") and return more than intended."""
    return _execute_on_read_only_connection(sql, params, db_path)
